openapi: 3.0.0

servers:
  - url: 'https://localhost:8080/api/v1'
    description: server

info:
  title: Book Store API
  version: 1.0.0
  description: A simple API for managing books, authors, and reviews.

paths:
  /books:
    get:
      operationId: booksGET
      summary: List all books
      responses:
        200:
          description: A list of books
          content:
            application/json:
              schema:
                $ref: 'schemas/booksList.yaml'
    post:
      operationId: booksPOST
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/book.yaml'
      responses:
        201:
          description: Book created

  /books/{bookId}:
    get:
      operationId: booksBookIdGET
      summary: Get details of a book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          description: The ID of the book
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Detailed information about the book
          content:
            application/json:
              schema:
                $ref: 'schemas/book.yaml'

  /authors:
    get:
      operationId: authorsGET
      summary: List all authors
      responses:
        200:
          description: A list of authors
          content:
            application/json:
              schema:
                $ref: 'schemas/authorsList.yaml'
    post:
      operationId: authorsPOST
      summary: Add a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/author.yaml'
      responses:
        201:
          description: Author created

  /reviews:
    get:
      operationId: reviewsGET
      summary: List all reviews
      responses:
        200:
          description: A list of reviews
          content:
            application/json:
              schema:
                $ref: 'schemas/reviewsList.yaml'
    post:
      operationId: reviewsPOST
      summary: Add a new review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/review.yaml'
      responses:
        201:
          description: Review created
